version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch1
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms20000m -Xmx20000m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch2,elasticsearch3,elasticsearch4"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 40g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch2
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms20000m -Xmx20000m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch3,elasticsearch4"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 40g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9301:9300
    networks:
      - esnet
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch3
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms20000m -Xmx20000m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch4"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 40g
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9302:9300
    networks:
      - esnet
  elasticsearch4:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch4
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - node.name=elasticsearch4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms20000m -Xmx20000m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1,elasticsearch2,elasticsearch3"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 40g
    volumes:
      - esdata4:/usr/share/elasticsearch/data
    ports:
      - 9303:9300
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  esdata4:
    driver: local

networks:
  esnet:
